### ISSUE TITLE
Please add the architecture to the Linux file name

### ISSUE THREAD

**Issue by probonopd** [noisymime/SpeedyLoader#1]
Please add the architecture to the Linux file name, e.g., `i686` or `x86_64`.

**Comment by noisymime** [comment]
Good call. 
Done for the v1.0 release.

**Comment by probonopd** [comment]
Why `i686` and not `x86_64`?

**Comment by noisymime** [comment]
There's a few of the dependency files that come through as x86 by default. Probably fairly easy to fix, but hasn't been a priority.
This version should run just fine on x86_64 linux systems though, it certainly has on mine in testing.

**Comment by probonopd** [comment]
Perhaps, but i686 means "32 bit" whereas x86_64 means "64 bit".
